### model
model_name_or_path: ../role_bench_result/llama3_lora_reasonsft_aware_rbench/merge_model_qlora
quantization_bit: 4
quantization_method: bitsandbytes  # choices: [bitsandbytes (4/8), hqq (2/3/4/5/6/8), eetq (8)]

### method
stage: dpo
do_train: true
finetuning_type: lora
lora_target: all
lora_alpha: 16
lora_dropout: 0.1
lora_rank: 64
pref_beta: 0.1
pref_loss: sigmoid  

### dataset
dataset: rolebench_train_main_datas_best_specific_with_aware_reason_contrastive, rolebench_train_main_datas_best_general_with_aware_reason_contrastive
template: llama3
cutoff_len: 7096
max_samples: 3000
preprocessing_num_workers: 16


### output
output_dir: ../role_bench_result/llama3_lora_reasonsft_aware_rbench_contrastive
logging_steps: 1
save_steps: 100
plot_loss: true
overwrite_output_dir: true
save_total_limit: 30

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
learning_rate: 5.0e-5
num_train_epochs: 1
lr_scheduler_type: cosine
warmup_ratio: 0.03
bf16: true
ddp_timeout: 180000000
flash_attn: fa2
weight_decay: 0.1
max_grad_norm: 1.0
disable_gradient_checkpointing: true

### eval
val_size: 0.01
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 100
